### ISSUE TITLE
Sleepy bar appears empty upon world join with certain config

### ISSUE THREAD

**Issue by Dune-Jumper** [CallMeFoxie/BetterSleeping2#5]
If you have _I:sleepOnGroundAt=_ set to -1, the sleepy bar appears empty upon joining a world, and it doesn't show properly until you either die and respawn or sleep.

Also I have an unrelated request: Can you please add a config to remove the sleep on ground button from the controls? Even if you have it set so you don't fall asleep if you're too tired, the player can just press a button to sleep. I want to make ground sleeping impossible entirely so they have to make a bed.

**Comment by PitchBright** [comment]
@Dune-Jumper Please create a separate issue titled "Feature Request: ____". It's not fair to expect mod authors to remember an idea from an unrelated topic. The whole point of an author using an issue tracker, is so that they have an easy way of seeing what is on their to-do list. Otherwise they might as well just use the forums, and keep track of everybody's ideas and problems on a pad of paper at their desk.
